### ISSUE TITLE
Should Drop modify filename by default?

### ISSUE THREAD

**Issue by matryer** [matryer/drop#1]
Gimme can easily change the filename:

```
try.go -> ext_try.go
```

Should it? 

Simplicity would be appreciated, but how often are things likely to clash?

**Comment by wayneashleyberry** [comment]
My 2 cents, I far prefer adding files into a separate directory over renaming them.

**Comment by dsparkman** [comment]
I would think something along the lines of `username_repo_filename`

`try.go -> matryer_try_try.go`

**Comment by hermanschaaf** [comment]
My thoughts: It should not change the name by default (an option would be nice, of course.) If the `gimme` command detects it will result in a name conflict, it can warn the user and explain how to use the name change option.

**Comment by matryer** [comment]
Thanks for your comments.

re a sub-folder... why not just vendor the dependency then? The idea here is to take ownership of code, not another tool to maintain dependencies. Thoughts?

**Comment by matryer** [comment]
I thought of the `matryer_try_try.go` too, and while it's a bit ugly, sort of goes against the 'taking ownership' philosophy of this.
